# ConfigMap to expose configuration related to backend application
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-conf # name of configMap
data:
  server-host: 172.25.25.153
  server-port: "30002"
  server-uri: "http://172.25.25.153:30002" # enternal ip of backend application 'Service'

