# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: catalogue-app  
spec:
  selector: 
    app: catalogue-app
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3002
    targetPort: 3002
    nodePort: 30002
  type: NodePort 
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-app
  labels: 
    app: catalogue-app
    tier: backend
spec:
  replicas: 1   
  selector:
    matchLabels: 
      app: catalogue-app
      tier: backend
  template:
    metadata:
      labels: # Must macth 'Service' and 'Deployment' labels
        app: catalogue-app
        tier: backend  
    spec:                 
      containers: 
      - name: catalogue-app 
        image: tochi2022/catalogue-app:11   
        env:   
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_ROOT_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-root-credentials
                key: password 
        ports:
        - containerPort: 3002