# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: cart-app  
spec:
  selector:  # backend application pod lables should match these
    app: cart-app
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3003
    targetPort: 3003
    nodePort: 30003
  type: NodePort   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
  labels: 
    app: cart-app
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: cart-app
      tier: backend
  template:
    metadata:
      labels: # Must macth 'Service' and 'Deployment' labels
        app: cart-app
        tier: backend  
    spec:                 
      containers: 
      - name: cart-app 
        image: tochi2022/cart-app:2.0   # docker image of backend application 
        ports:
        - containerPort: 3003