# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: cart-app  
spec:
  selector:  
    app: cart-app
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3003
    targetPort: 3003
    nodePort: 30003
  type: NodePort  
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
  labels: 
    app: cart-app
    tier: backend
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: cart-app
      tier: backend
  template:
    metadata:
      labels: 
        app: cart-app
        tier: backend  
    spec:                 
      containers: 
      - name: cart-app 
        image: tochi2022/cart-app:2.0  
        ports:
        - containerPort: 3003