# Define 'Configmap' to store non-sensitive database configuration 
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf  # name of ConfigMap, referenced in other files
data:
  host: mysql  
  name: shop # name of the database for application
